### ISSUE TITLE
Work on Credit Card Analysis

### ISSUE THREAD

**Issue by austinPeel0** [GSA/travel-project-report#3]
Provide analysis on credit_analysis.py.

 Certain columns were removed to clean up the dataframe. You can find the exhaustive list in utils/columns.py change to keep = True if you want to display the column in the dataframe.

columns are aggregated by type found in columns.py as well

**Comment by csmcallister** [comment]
If we can assume that records in the travel card dataset with either a 0 or nan for `M&IE-PerDiem_card` are folks that used cash/personal credit cards instead of gov-issued cards for their M&IE, then we test the null hypothesis that there's no significant difference in M&IE spending for smart-card users vs cash/personal credit card users. The alternative hypothesis is that there is some difference. But, in order to properly carry out this test, we need some more trip-level data, such as the travel destination, dates, etc. These extra variables will function as controls.
